<section class="section">
  <div class="container has-text-centered is-centered">
    <div class="box">
      <!-- <nav class="level is-mobile"> -->
        <!-- <div class="level-item has-text-centered"> -->
          <table class="table is-fullwidth">
            <thead>
              <tr>
                <th>Recently</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>
                    <?php
                    if (isset($_SESSION["recently"] ))
                    {
                      echo $_SESSION["recently"];
                    }
                    else
                    {
                      $_SESSION["recently"] = "spa";
                      echo $_SESSION["recently"];
                    }
                    ?>
                  </td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="/play/<?php echo $_SESSION["recently"]; ?>">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
            </tbody>
          </table>
        <!-- </div> -->
      <!-- </nav> -->
    </div>
    <hr>
    <div class="box">
      <!-- <nav class="level is-mobile"> -->
        <!-- <div class="level-item has-text-centered"> -->
          <table class="table is-fullwidth">
            <thead>
              <tr>
                <th>Category</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Lullaby</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="playlist/lullaby">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Tales</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="playlist/tales">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>The Shock</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="playlist/theshock">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
            </tbody>
          </table>
        <!-- </div> -->
      <!-- </nav> -->
    </div>
    <hr>
    <a href="/entercode" class="button is-primary">Logout</a>
    </div>

  </section>
