//มะใช้งาบ //
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  </head>
  <body>

    <aside class="menu">
      <a class="navbar-link" role="navigation">
        Home
      </a>
      <a class="navbar-link" role="navigation">
        Recents
      </a>
      <div class="navbar-dropdown">
        <a class="navbar-item">
          song 1
        </a>
        <a class="navbar-item">
          song 2
        </a>
        <a class="navbar-item">
          song 3
        </a>
      <nav class="navbar" role="navigation" aria-label="dropdown navigation">
          <div class="navbar-item has-dropdown is-hoverable">

            <a class="navbar-link">
              Categories
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                Lullaby
              </a>
              <a class="navbar-item">
                Tale
              </a>
              <a class="navbar-item">
                Ghost Story
              </a>

            </div>
          </div>
</nav>
</aside>
  </body>
</html>
