<section class="section">

      <div class="container">
    <div class="columns">
    <div class="column is-half is-offset-one-quarter">
      <div class="box has-text-centered">
          <img src="/image/bg.png" alt="">
        <label class="label has-text-centered" >Huggy</label>
        <div class="column is-half is-offset-one-quarter">
          <input class="input" type="text" placeholder="Please Enter your Bearcode">
        </div>
          <div class="buttons is-medium has-addons is-centered">
            <span class="button">Log In</span>

      </div>


  </div>
</section>
