<section class="section">
  <div class="container has-text-centered is-centered">
    <h1 class="title is-1">Song Name</h1>
    <br>
    <h2 class="subtitle">Song Writer</h2>
    <hr></hr>
    <h2 class="subtitle is-3 has-text-left">Play Sample</h1>
    <div class="box">
      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <span class="icon has-text-danger">
            <i class="fas fa-play-circle fa-4x"></i>
          </span>
        </div>
      </nav>
    </div>

    <h2 class="subtitle is-3 has-text-left">Full Song</h1>

    <div class="box">
      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <span class="icon has-text-danger">
            <i class="fas fa-play-circle fa-4x"></i>
          </span>
        </div>
      </nav>
    </div>
  </section>

  <!-- <table class="table is-fullwidth"> line 6 to 23
    <thead>
      <tr>
        <th>Play Sample</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <nav class="level is-mobile">
          <div class="level-item has-text-centered">
            <td><span class="icon has-text-danger">
              <i class="fas fa-play-circle"></i>
            </span></td>
          </div>
        </nav>
      </tr>
    </tbody>
  </table> -->
