<section class="section">
    <div class="container">
        <div class="columns is-mobile">
            <div class="column is-6">
                <div class="card" id="card-on-online">
                    <a href="/dashboard/turnOn">
                        <div class="card-content has-text-centered">
                            <span class="icon">
                                <i class="far fa-lightbulb fa-2x fa-inverse"></i>
                            </span>
                        </div>
                    </a>
                </div>
            </div>
            <div class="column is-6">
                <div class="card" id="card-off-online">
                    <a href="/dashboard/turnOff">

                  <div class="card-content">
                      <span class="icon">
                          <i class="far fa-lightbulb fa-2x fa-inverse"></i>
                      </span>
                  </div>
              </a>

                </div>
            </div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-6">
                <div class="card" id="card-offline">
                  <div class="card-content">


                  </div>
                </div>
            </div>
        </div>

    </div>
</section>
