<section class="section">
  <div class="container has-text-centered is-centered">
    <hr>
    <div class="box">
      <!-- <nav class="level is-mobile"> -->
        <!-- <div class="level-item has-text-centered"> -->
          <table class="table is-fullwidth">
            <thead>
              <tr>
                <th>The Shock</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Story 01</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="/play/story1">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Story 02</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="/play/story2">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
            </tbody>
          </table>
        <!-- </div> -->
      <!-- </nav> -->
    </div>
    <hr>
    </div>
  </section>
