<section class="section">
  <div class="container has-text-centered is-centered">
    <hr>
    <div class="box">
      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <table class="table is-fullwidth">
            <thead>
              <tr>
                <th>CategoryNamed</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Song1</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="play">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Song2</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="play">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
                <nav class="level is-mobile">
                  <div class="level-item has-text-centered">
                    <td>Song3</td>
                  </div>
                  <div class="level-item has-text-centered">
                    <td>
                      <a href="play">
                        <span class="icon has-text-danger">
                        <i class="fas fa-play"></i>
                      </a>
                    </td>
                  </div>
                </nav>
              </tr>
              <tr>
            </tbody>
          </table>
        </div>
      </nav>
    </div>
    <hr>
    </div>
  </section>
